export const TYRE_COLORS: Record<string, string> = {
  SOFT: "#FF3333",
  MEDIUM: "#FFC906",
  HARD: "#FFFFFF",
  INTERMEDIATE: "#39B54A",
  WET: "#0067FF",
  S: "#FF3333",
  M: "#FFC906",
  H: "#FFFFFF",
  I: "#39B54A",
  W: "#0067FF",
  C5: "#FF3333",
  C4: "#FF3333",
  C3: "#FFC906",
  C2: "#FFFFFF",
  C1: "#FFFFFF",
  C0: "#FFFFFF",
};

export const TYRE_SHORT: Record<string, string> = {
  SOFT: "S",
  MEDIUM: "M",
  HARD: "H",
  INTERMEDIATE: "I",
  WET: "W",
  S: "S",
  M: "M",
  H: "H",
  I: "I",
  W: "W",
  C5: "S",
  C4: "S",
  C3: "M",
  C2: "H",
  C1: "H",
  C0: "H",
};

export const SPEED_OPTIONS = [0.5, 1, 2, 5, 10, 20];

export const TEAM_ABBR: Record<string, string> = {
  "Red Bull Racing": "RBR",
  "Mercedes": "MER",
  "Ferrari": "FER",
  "McLaren": "MCL",
  "Aston Martin": "AMR",
  "Alpine": "ALP",
  "Williams": "WIL",
  "Racing Bulls": "RBU",
  "RB": "RBU",
  "Haas F1 Team": "HAA",
  "Kick Sauber": "SAU",
  "Audi": "AUD",
  "Cadillac": "CAD",
};
